---
# handlers file for postfix
- name: rebuild alias database
  command: postmap "{{ postfix_alias_path }}"

- name: rebuild sender_access database
  command: postmap "{{ postfix_sender_access_path }}"

- name: rebuild recipient_access database
  command: postmap "{{ postfix_recipient_access_path }}"

- name: restart postfix
  service:
    name: "{{ postfix_service }}"
    state: restarted

- name: create selinux mod for postfix
  command: checkmodule -M -m -o /etc/my-postfix.mod /etc/my-postfix.te

- name: create selinux pp for postfix
  command: semodule_package -o /etc/my-postfix.pp -m /etc/my-postfix.mod

- name: load selinux pp for postfix
  command: semodule -i /etc/my-postfix.pp
